sudo: false

language: python

python:
  - 3.6

install:
  - pip install -r ./requirements.tests.txt
  - pip install -r ./shortify/requirements.txt
  - pip install -r ./blacklist/requirements.txt

script:
  - pytest --cov=./shortify/ --cov=./blacklist/ .

after_success:
  - codecov

before_script: sudo redis-server /etc/redis/redis.conf --port 6666
