sudo: false

language: python

python:
  - 3.6

install:
  - pip install codecov,pytest
  - pip install -r ./shortify/requirements.txt

script:
  - coverage run ./shortify/tests.py

after_success:
  - codecov

services:
  - redis-server
