sudo: false

language: python

python:
  - 3.6

install:
  - pip install -r ./requirements.tests.txt
  - pip install -r ./shortify/requirements.txt

script:
  - pytest --cov=./shortify/ ./shortify/test_shortify.py

after_success:
  - codecov

services:
  - redis-server
